import type {Product} from "../types/index.ts";
import {Farm} from "../types/index.ts";
import FarmPage from "../pages/FarmPage.tsx";

export const mockProducts: Product[] = [
    {
        id: 1,
        category: 'Diary',
        title: 'Yogurt',
        description: 'Fresh yogurt',
        amount: 20,
        price: 3,
        units: 'kg',
        farm: FarmPage,
        imageUrl: '/src/assets/yogurt.jpg',
    },
    {
        id: 2,
        category: 'Fruits',
        title: 'Oranges',
        description: 'Fresh oranges',
        amount: 30,
        price: 4,
        units: 'kg',
        farm: FarmPage,
        imageUrl: '/src/assets/orange.jpg',
    },
    {
        id: 3,
        category: 'Vegetables',
        title: 'Tomatoes',
        description: 'Fresh tomatoes',
        amount: 100,
        price: 2.5,
        units: 'kg',
        farm:FarmPage,
        imageUrl: '/src/assets/tomat.jpg'
    },

    {
        id: 4,
        category: 'Diary',
        title: 'Cheese',
        description: 'Fresh cheese',
        amount: 200,
        price: 26,
        units: 'kg',
        farm:FarmPage,
        imageUrl: '/src/assets/cheese.jpg',
    },
    {
        id: 5,
        category: 'Pantry',
        title: 'Honey',
        description: 'Fresh honey',
        amount: 88,
        price: 60,
        units: 'kg',
        farm:FarmPage,
        imageUrl: '/src/assets/honey.jpg',
    },
    {
        id: 6,
        category: 'herbs',
        title: 'Honey',
        description: 'Fresh roses',
        amount: 88,
        price: 20,
        units: 'jar',
        farm:FarmPage,
        imageUrl: '/src/assets/rose.jpg',
    },
    {
        id: 7,
        category: 'Herbs',
        title: 'Basil',
        description: 'Fresh roses',
        amount: 88,
        price: 20,
        units: 'kg',
        farm:FarmPage,
        imageUrl: '/src/assets/basil.jpg',
    },
    {
        id: 8,
        category: 'Vegetables',
        title: 'Cucumbers',
        description: 'Fresh cucumbers',
        amount: 100,
        price: 2.5,
        units: 'kg',
        farm:FarmPage,
        imageUrl: '/src/assets/cucumber.jpg',
    },
    {
        id: 9,
        category: 'Herbs',
        title: 'Mint',
        description: 'Fresh mint',
        amount: 88,
        price: 20,
        units: 'kg',
        farm:FarmPage,
        imageUrl: '/src/assets/mint.jpg',
    },
    {
        id: 2,
        category: 'Fruits',
        title: 'Avocado',
        description: 'Fresh avocado',
        amount: 30,
        price: 4,
        units: 'kg',
        farm:FarmPage,
        imageUrl: '/src/assets/avocado.jpg',
    },
]