import type { Farm } from '../types/';

export const mockFarms: Farm[] = [
    {
        id: 1,
        name: 'Good farm',
        location: 'Gush Dan',
        city: 'Tel-Aviv',
        rating: 4.8,
        isVerified: true,
        description: 'We offer only fresh and organic mockProducts from our farm',
        phone: '123-456-7890',
        email: 'good.farm@example.com',
        products: [],
    },
    {
        id: 2,
        name: 'Botanic farm',
        location: 'Gush Dan',
        city: 'Tel-Aviv',
        rating: 4.2,
        isVerified: true,
        description: 'We offer not only fresh and organic verbs, but also flowers and plants.',
        phone: '123-456-7891',
        email: 'botanic.farm@example.com',
        products: [],
    },
    {
        id: 3,
        name: 'Bad farm',
        location: 'North District',
        city: 'Haifa',
        rating: 4.0,
        isVerified: true,
        description: 'We offer only fresh and tasty citrus fruits',
        phone: '123-456-7892',
        email: 'bad.farm@example.com',
        products: [],
    },
    {
        id: 4,
        name: 'Mad farm',
        location: 'North District',
        city: 'Haifa',
        rating: 5.0,
        isVerified: true,
        description: 'We offer only trulala and trololo! Enjoy!',
        phone: '123-456-7893',
        email: 'mad.farm@example.com',
        products: [],
    },
    {
        id: 5,
        name: 'Good farm',
        location: 'Haifa',
        city: 'Haifa',
        rating: 4.0,
        isVerified: true,
        description: 'We offer the best mockProducts from our farm',
        phone: '123-456-7894',
        email: 'good.haifa.farm@example.com',
        products: [],
    },
    {
        id: 6,
        name: 'Good farm',
        location: 'Haifa',
        city: 'Haifa',
        rating: 4.7,
        isVerified: true,
        description: 'Best organic goods from our farm',
        phone: '123-456-7895',
        email: 'best.haifa.farm@example.com',
        products: [],
    },
    {
        id: 7,
        name: 'Good farm',
        location: 'Haifa',
        city: 'Haifa',
        rating: 4.7,
        isVerified: true,
        description: 'Best for your family from our farm with love',
        phone: '123-456-7896',
        email: 'family.haifa.farm@example.com',
        products: [],
    },
];